#!/usr/bin/env python3
# Copyright (c) 2026 Adrian Vos (soveda). SPDX-License-Identifier: MIT
# Measurements: Gardner & Martin, MIT Media Laboratory, copyright 1994.
# Source/terms: https://sound.media.mit.edu/resources/KEMAR.html
"""Rebuild 48 kHz horizontal minimum-phase KEMAR banks (32 and 64 taps).
Requires NumPy/SciPy. The retained diffuse.zip archive is not edited.
"""
import hashlib, io, json, pathlib, wave, zipfile
import numpy as np
from scipy.signal import resample_poly
ROOT=pathlib.Path(__file__).resolve().parents[1]
ARCHIVE=ROOT/'vendor/KEMAR/diffuse.zip'
# Keep the alpha4 32-tap bank gain for both profiles: meaningful level-matched A/B.
SCALE=0.48727477260326996
archive=zipfile.ZipFile(ARCHIVE)
responses=[]
for degree in range(0,360,5):
    az=degree if degree<=180 else 360-degree
    with wave.open(io.BytesIO(archive.read(f'elev0/H0e{az:03d}a.wav'))) as w:
        assert (w.getframerate(),w.getnchannels(),w.getsampwidth())==(44100,2,2)
        h=np.frombuffer(w.readframes(w.getnframes()),dtype='<i2').reshape(-1,2)/32768.
    if degree>180:h=h[:,::-1]
    h=resample_poly(h,160,147,axis=0)
    ears=[]
    for ear in range(2):
        magnitude=np.maximum(np.abs(np.fft.rfft(h[:,ear],2048)),1e-5)
        cep=np.fft.irfft(np.log(magnitude),2048)
        lifted=np.zeros(2048);lifted[0]=cep[0];lifted[1:1024]=2*cep[1:1024];lifted[1024]=cep[1024]
        minimum=np.fft.irfft(np.exp(np.fft.rfft(lifted)),2048)
        ears.append((magnitude,minimum))
    responses.append(ears)
report={'archive_sha256':hashlib.sha256(ARCHIVE.read_bytes()).hexdigest(),'profiles':{}}
for taps in (32,64):
    raw=np.array([[e[1][:taps].copy() for e in d] for d in responses])
    raw[:,:,-8:]*=np.cos(np.linspace(0,np.pi/2,8))**2
    q=np.rint(raw*SCALE*16384).astype(np.int32)
    assert np.max(np.abs(q))<=32767
    # Bound partially updated coefficients and the neutral impulse; a small
    # rounding allowance covers interpolation and Q12 strength-blend rounding.
    maxima=np.max(np.abs(q),axis=0)+2;maxima[:,0]=np.maximum(maxima[:,0],16384)
    bound=int(maxima.sum(axis=1).max())
    assert bound*4096<2**31 and (bound*4096>>14)<32768
    freq=np.fft.rfftfreq(2048,1/48000);band=(freq>=1000)&(freq<=12000)
    errors=[];retained=[]
    for d,direction in enumerate(responses):
        for e,(reference,minimum) in enumerate(direction):
            got=np.abs(np.fft.rfft(q[d,e]/16384,2048))
            err=20*np.log10(np.maximum(got,1e-5)/(reference*SCALE))
            errors.extend(err[band]);retained.append(float(np.sum(minimum[:taps]**2)/np.sum(minimum**2)))
    lines=['// Generated by tools/generate_hrtf.py; do not edit.',
      '// Measurements (c) 1994 MIT Media Laboratory: Bill Gardner and Keith Martin.',
      '// Data usage terms and citation: vendor/KEMAR/SOURCE_TERMS.md.',
      '// Generator (c) 2026 Adrian Vos (soveda), MIT. Data retains its own terms.',
      '#pragma once','#include <cstdint>','namespace spatial {',
      f'constexpr int kHrtfDirections=72, kHrtfTaps={taps};',
      f'constexpr int kHrtfMixtureL1Bound={bound};',
      f'alignas(4) constexpr int16_t kHrtf[72][2][{taps}] = {{']
    for direction in q:lines.append('  {'+','.join('{'+','.join(map(str,ear))+'}' for ear in direction)+'},')
    lines.extend(['};','}'])
    (ROOT/f'src/dsp/hrtf_table_{taps}.h').write_text('\n'.join(lines)+'\n')
    report['profiles'][str(taps)]={'directions':72,'elevation_degrees':0,'rate':48000,'taps':taps,'q_fraction_bits':14,
      'global_scale':SCALE,'max_direction_ear_l1':float(np.max(np.sum(np.abs(q)/16384,axis=2))),
      'worst_mixture_l1_q14':bound,'min_energy_retained_before_taper':min(retained),
      'magnitude_error_1k_12k_rms_db':float(np.sqrt(np.mean(np.array(errors)**2))),
      'magnitude_error_1k_12k_p95_abs_db':float(np.percentile(np.abs(errors),95))}
(ROOT/'vendor/KEMAR/generation.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
