#!/usr/bin/env python3
# Copyright (c) 2026 Adrian Vos (soveda). SPDX-License-Identifier: MIT
# Derived measurements: Gardner & Martin, MIT Media Laboratory, copyright 1994.
# Source/terms: https://sound.media.mit.edu/resources/KEMAR.html
"""Rebuild the 48 kHz / 32-tap horizontal minimum-phase KEMAR bank.
Requires numpy and scipy. Original diffuse.zip is retained, not edited.
"""
import hashlib, io, json, pathlib, wave, zipfile
import numpy as np
from scipy.signal import resample_poly
ROOT=pathlib.Path(__file__).resolve().parents[1]
ARCHIVE=ROOT/'vendor/KEMAR/diffuse.zip'
TAPS=32
archive=zipfile.ZipFile(ARCHIVE)
responses=[]
for degree in range(0,360,5):
    # Compact/diffuse files cover the right hemisphere; mirror and swap ears.
    az=degree if degree<=180 else 360-degree
    with wave.open(io.BytesIO(archive.read(f'elev0/H0e{az:03d}a.wav'))) as w:
        assert (w.getframerate(),w.getnchannels(),w.getsampwidth())==(44100,2,2)
        h=np.frombuffer(w.readframes(w.getnframes()),dtype='<i2').reshape(-1,2)/32768.
    if degree>180:h=h[:,::-1]
    h=resample_poly(h,160,147,axis=0)
    ears=[]
    for ear in range(2):
        # Minimum phase retains measured magnitude while removing transport delay.
        # ITD is rendered separately in the firmware; it is not counted twice.
        magnitude=np.maximum(np.abs(np.fft.rfft(h[:,ear],2048)),1e-5)
        cep=np.fft.irfft(np.log(magnitude),2048)
        lifted=np.zeros(2048);lifted[0]=cep[0];lifted[1:1024]=2*cep[1:1024];lifted[1024]=cep[1024]
        minimum=np.fft.irfft(np.exp(np.fft.rfft(lifted)),2048)
        shortened=minimum[:TAPS].copy()
        shortened[-8:]*=np.cos(np.linspace(0,np.pi/2,8))**2
        ears.append((shortened,magnitude,minimum))
    responses.append(ears)
# One shared scale preserves direction/ear level differences. Bound all time-
# varying coefficient mixtures, including partially updated vectors, in int32.
raw=np.array([[ear[0] for ear in direction] for direction in responses])
scale=min(1.,2.5/np.max(np.sum(np.abs(raw),axis=2)))
q=np.rint(raw*scale*16384).astype(np.int32)
assert np.max(np.abs(q))<=32767
maxima=np.max(np.abs(q),axis=0);maxima[:,0]=np.maximum(maxima[:,0],16384)
bound=int(maxima.sum(axis=1).max())
assert bound*4096<2**31
freq=np.fft.rfftfreq(2048,1/48000);band=(freq>=1000)&(freq<=12000)
errors=[];retained=[]
for d,direction in enumerate(responses):
    for e,(_,reference,minimum) in enumerate(direction):
        got=np.abs(np.fft.rfft(q[d,e]/16384,2048))
        err=20*np.log10(np.maximum(got,1e-5)/(reference*scale))
        errors.extend(err[band]);retained.append(float(np.sum(minimum[:TAPS]**2)/np.sum(minimum**2)))
lines=['// Generated by tools/generate_hrtf.py; do not edit.',
       '// Measurements (c) 1994 MIT Media Laboratory: Bill Gardner and Keith Martin.',
       '// Data usage terms and citation: vendor/KEMAR/SOURCE_TERMS.md.',
       '// Generator (c) 2026 Adrian Vos (soveda), MIT. Data retains its own terms.',
       '#pragma once','#include <cstdint>','namespace spatial {',
       'constexpr int kHrtfDirections=72, kHrtfTaps=32;',
       f'constexpr int kHrtfMixtureL1Bound={bound};',
       'alignas(4) constexpr int16_t kHrtf[72][2][32] = {']
for direction in q:lines.append('  {'+','.join('{'+','.join(map(str,ear))+'}' for ear in direction)+'},')
lines.extend(['};','}'])
(ROOT/'src/dsp/hrtf_table.h').write_text('\n'.join(lines)+'\n')
report={'archive_sha256':hashlib.sha256(ARCHIVE.read_bytes()).hexdigest(),
        'directions':72,'elevation_degrees':0,'rate':48000,'taps':32,'q_fraction_bits':14,
        'global_scale':scale,'worst_mixture_l1_q14':bound,
        'min_energy_retained_first32_before_taper':min(retained),
        'magnitude_error_1k_12k_rms_db':float(np.sqrt(np.mean(np.array(errors)**2))),
        'magnitude_error_1k_12k_p95_abs_db':float(np.percentile(np.abs(errors),95))}
(ROOT/'vendor/KEMAR/generation.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
